### ISSUE TITLE
Private repos

### ISSUE THREAD

**Issue by infinitepower18** [chaNcharge/ForkUpdater#2]
Hi, does this work with private repos?

**Comment by Macleykun** [comment]
![image](https://user-images.githubusercontent.com/26381427/61148000-198ee180-a4de-11e9-9597-355df42b9a82.png)
not sure, but try giving the token your making full control of private repo's.
Fill in the same details like you would do on public repo's.

Should work.

**Comment by infinitepower18** [comment]
> ![image](https://user-images.githubusercontent.com/26381427/61148000-198ee180-a4de-11e9-9597-355df42b9a82.png)
> not sure, but try giving the token your making full control of private repo's.
> Fill in the same details like you would do on public repo's.
> 
> Should work.

I’ve done this, but when running `bash ./update.sh` in Heroku it asks for GitHub username and password login. I’m not sure if that’s part of how the script works.

**Comment by chaNcharge** [comment]
I believe line 9 on the script is causing issues, where the script runs `git clone`, as its trying to clone a private repo it doesn't have access to. I didn't fully design this with private repos in mind. You could probably change the url in the clone command to the same format as the `push_uri` variable, and it might start working.
