### ISSUE TITLE
heroku support?

### ISSUE THREAD

**Issue by mishailovic** [chaNcharge/ForkUpdater#3]
How can i deploy this on a heroku? Help me please.

**Comment by Macleykun** [comment]
First: Add update.sh to your repository
Second: deploy to Heroku
Third: add these env variables trough the settings tab
GITHUB_REPO: Your repo; part of the link after https://github.com/ (e.g chaNcharge/avaire).
GITHUB_REPO_BRANCH: Your repo's branch name to merge into.
GITHUB_SECRET_TOKEN: Your personal access token, the token will need public repo permissions. You can create one here.
UPSTREAM_REPO: The upstream repo to update from; part of the link after https://github.com/ (e.g chaNcharge/avaire).
UPSTREAM_BRANCH: The upstream repo's branch name to update from.
Fourth: Add under add-ons the Heroku Scheduler and to be sure, use bash ./path/to/update.sh
If you can do chmod +x on the update.sh before ya push it to heroku (you can save this in your github repo) you can actually do ./path/to/update.sh and it will be executed every time.

That's all to it.

**Comment by mishailovic** [comment]
Thank you very much, I will try.

**Comment by Macley-Kun** [comment]
Don’t forget to close the issue aswell

Met vriendelijke groet,

Wesley de Vree
________________________________
Van: Mikhail Kuznetsov <notifications@github.com>
Verzonden: Tuesday, March 31, 2020 8:21:06 PM
Aan: chaNcharge/ForkUpdater <ForkUpdater@noreply.github.com>
CC: Macley <wesley.de.vree@gmail.com>; Comment <comment@noreply.github.com>
Onderwerp: Re: [chaNcharge/ForkUpdater] heroku support? (#3)


Thank you very much, I will try.

**Comment by mishailovic** [comment]
👍

**Comment by mishailovic** [comment]
Thank you so much, everything works great!
